[project]
name = "fastapi-finance-api"
version = "0.1.0"
description = "Track personl income and expenses"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.0",
]
